application/__init__.py
from flask import Flask 

from flask_sqlalchemy import SQLAlchemy
from flask_socketio import SocketIO, send, emit

db = SQLAlchemy()
socketio = SocketIO()

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.secret_key = 'gizli'
    db.init_app(app)
    socketio.init_app(app)

    from .views import bp
    app.register_blueprint(bp)


    return app

application/views.py
from flask import Flask, render_template, redirect, url_for, session, Blueprint, request, g
from sqlalchemy import delete
import json
from werkzeug.wrappers import PlainRequest

from application import db, socketio
from application.database import Message, User, Room, members

from functools import wraps

from application.viewHandlers import (get_room, get_current_userId, get_current_userObject, if_logged, login_required, userInRoom
                                     ,userInRoom, get_rooms, get_room_byLink)

from flask_socketio import SocketIO, send, emit

bp = Blueprint('views', __name__)



@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id).first()


@bp.route('/', methods=('POST', 'GET',))
@if_logged
def index():
    if request.method == 'POST':
        username = request.form['username']
        new_user = User(name=username)
        
        db.session.add(new_user)
        db.session.commit()
        #session['user_object'] = new_user
        session['username'] = username
        session['user_id'] = new_user.id

        return redirect('main')

    return render_template('index.html')

@bp.route('/main')
@login_required
def main():

    data = {
        'room':'lala'
    }
    return render_template('main.html', data=data)


@bp.route('/create-room', methods=('POST', 'GET'))
@login_required
def create_room():
    if request.method == 'POST':
        password = None
        
        name = request.form['username']
        try:
         if request.form['isProtected'] == "on":
            is_protected = True 
            password = request.form['password']      
        except:
            is_protected = False
            password = None            
        
        try:
            if request.form['all_super'] == "on":
                all_super = True
        except:
            all_super= False
        

        max_users = request.form['max_users']

        current_userId = get_current_userId()
        
        if is_protected:
            print('protected')
            new_room = Room(name=name, 
                        password=password, all_super=all_super, max_users=max_users, creator_id=current_userId, protected=True)
            #new_room.set_hash()
        else:
            print('not protected')
            new_room = Room(name=name, 
                        all_super=all_super, max_users=max_users, creator_id=current_userId)

        
        db.session.add(new_room)
        db.session.commit()
        
        current_userObj = get_current_userObject()
        room_id = new_room.id

        new_room.users.append(current_userObj)

        db.session.commit()
        db.session.query(members).filter(
        members.c.user_id==current_userId, members.c.room_id==room_id).update((current_userId,room_id,True))
        db.session.commit()
        
        session['room_id'] = room_id
        new_room.generate_link()
        

        return redirect( url_for('views.rooms', link=new_room.link))
        
        
    return render_template('createRoom.html')




@bp.route('/join-room', methods=('GET', 'POST'))
@login_required
def join_room():
    if request.method == 'POST':
        error = None
        room = None
        try:
            password = request.form['password']
        except:
            password = None

        link = request.form['link']

        room = get_room_byLink(link)
        if not room:
            error = 'This link does not belong to any room'
            return redirect(url_for('views.error', error_msg= error))
        else:

            check_user_in = userInRoom(room)
            if not check_user_in:
                is_protected = room.protected
                
                if is_protected:
                    if password:
                        print(room.check_pass(password), 'here')
                        if room.check_pass(password):
                            print('right pass')
                            current_userObj = get_current_userObject()
                            room.users.append(current_userObj)
                            db.session.commit()
                            
                            db.session.query(members).filter(
                            members.c.user_id==room.creator_id, members.c.room_id==room.id).update((room.creator_id, room.id, room.all_super))
                            db.session.commit()

                            session['room_id'] = room.id
                        else:
                            
                            error = 'Wrong password.'
                            return redirect(url_for('views.error', error_msg= error))


                    else:
                        
                        error = 'This room is protected with a password.'
                        return redirect(url_for('views.error', error_msg= error))
                else:

                    current_userObj = get_current_userObject()
                    room.users.append(current_userObj)
                    db.session.commit()
                    
                    db.session.query(members).filter(
                    members.c.user_id==room.creator_id, members.c.room_id==room.id).update((room.creator_id, room.id, room.all_super))
                    db.session.commit()

                    session['room_id'] = room.id

            return redirect(url_for('views.rooms', link=link))

        
    return render_template('joinRoom.html')


@bp.route('/error/<error_msg>')
def error(error_msg):
    return render_template('error.html', error_msg=error_msg)

@bp.route('/room/<link>')
@login_required
def rooms(link):
    error = None
    room = None

    room = get_room_byLink(link)

    if not room:
        error = 'This link does not belong to any room'
        return redirect(url_for('views.error', error_msg=error))
    
    check_user_in = userInRoom(room)
    if not check_user_in:
        error = 'You can not join this room unless a super user gives you the join link.'
        return redirect(url_for('views.error', error_msg= error))

    messages = Message.query.filter_by(roomPid=room.id).all()
    print(messages)
    data = {
        'room':room,
        'messages':messages
    }
    return render_template('room.html', data=data)
    

@bp.route('/leave-room', methods=('POST',))
def leave_room():
    if request.method == 'POST':
        print('leave 1')
        try:
            user_id = request.get_json()['user_id']
            room_id = int(request.get_json()['room_id'])
        except:
            user_id = None
            room_id = None
        print(user_id, room_id)
        db.session.query(members).filter(members.c.user_id==user_id, members.c.room_id==room_id).delete()
        db.session.commit()

        session.pop('room_id')
        user =get_current_userObject()
        user = user.serialize()
        socketio.emit('leave room', user)
        
    
    return redirect(url_for('views.main'))


@bp.route('/get_user')
def get_user():

    user = get_current_userObject()
    user = user.serialize()
    data = {
        'user':user
    }
    return data or {}


@bp.route('/get-active-room')
def get_active_room():
    room = get_room()
    if room:
        room = room.serialize()

    return room or {}

application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>

        .createRoom-form
        {
           margin-top: 5%;
           margin-left: 33%;
           margin-right: 33%;
        }
        .main-btns
        {
            text-align: center;
            margin-top: 15%;
        }

        .create-btn
        {
            margin: 2%;
        }

        .join-btn
        {
            margin: 2%;
        }


    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{%block title%} {%endblock%}</title>
</head>
<body>
    {%block content%}

    {%endblock%}
    
</body>
<script>
    function handle_pass(){

      if ($('#hasPassword').is(':checked')) {

          var input = '<input type="password" class="form-control" id="password" name="password"  placeholder="Enter password"'
          var form_group = `<div class='pass-group form-group mt-3'>` + input + "</div>";
          $('.my-join-group').append(form_group)
          $("#passHelp").text('Switch this off if the room has no password.')
      } else {
        console.log($("#passHelp"))
          $(".pass-group").remove()
          $("#passHelp").text('Switch this on if the room has a password.')
      }
    }
    function handle_protect(){

        if ($('#isProtected').is(':checked')) {

            var input = '<input type="password" class="form-control" id="password" name="password"  placeholder="Enter password" required'
            var form_group = `<div class='protect-pass-group form-group mt-3'>` + input + "</div>";
            $('.my-create-group').append(form_group)
            $("#protectHelp").text('Switch this off if you want non protected room.')
        } else {
        console.log($("#passHelp"))
            $(".protect-pass-group").remove()
            $("#protectHelp").text('Switch this on if you want a protected room.')
        }
}

</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{{ url_for( 'static', filename='serverHandlers.js') }}"></script>
</html>

application/templates/createRoom.html
{% extends 'base.html' %}

{%block content%}

<form class="createRoom-form" method="POST">
  <div class="my-create-group">
      <div class="form-group">
        <label for="exampleInputEmail1">Name</label>
        <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">This will be your room's name.</small>
      </div>
  </div>
  <div class="form-check form-switch">
    <input onclick="handle_protect()" class="form-check-input" type="checkbox" id="isProtected" name="isProtected">
    <small id="protectHelp" class="form-text text-muted">Switch this on if you want a protected room.</small>
  </div>
    <select class="custom-select my-1 mr-sm-2" id="max_users" name="max_users">
      <option selected>Choose...</option>
      {% for i in range(12)%}
      <option value="{{i+1}}">{{i+1}}</option>

      {%endfor%}
    </select>
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" id="all_super" name="all_super">
      <small id="emailHelp" class="form-text text-muted">Make all members of room super members ? </small>
    </div>
    <button href="{{ url_for('views.create_room') }}" type="submit" class="submit-btn btn btn-primary" >Submit</button>
  </form>
{%endblock%}

application/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
    <h3>{{error_msg}}</h3>
</body>
</html>          

application/templates/index.html
{%extends 'base.html'%}


{%block content%}
<form method="POST"> 
    <div class="form-group" style="margin-right: 40%; margin-left: 40%; margin-top: 10%; text-align: center;">
      <label for="exampleInputEmail1">Pick a username</label>
      <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
      <small id="emailHelp" class="form-text text-muted">This will be your username.</small>
    </div>
    <button href="{{ url_for('views.index')}}" type="submit" class="btn btn-primary mt-1" style="margin-left: 47%;">Submit</button>
  </form>
{%endblock%}

application/templates/joinRoom.html
{% extends 'base.html' %}

{%block content%}

<form class="createRoom-form" method="POST">
    <div class="my-join-group">
        <div class="form-group">
        <label for="exampleInputEmail1">Enter the link</label>
        <input type="text" class="form-control" id="link" name="link" aria-describedby="emailHelp" placeholder="Enter link">
        <small id="emailHelp" class="form-text text-muted">You can get this link from a super member of the room.</small>
        </div>
    </div>
    <div class="form-check form-switch">
        <input onclick="handle_pass()" class="form-check-input" type="checkbox" id="hasPassword" name="hasPassword">
        <small id="passHelp" class="form-text text-muted">Switch this on if the room has a password.</small>
      </div>
    <button href="{{ url_for('views.join_room') }}" type="submit" class="submit-btn btn btn-primary mt-2" style="margin-left: 40%;" >Submit</button>
  </form>

{%endblock%}

application/templates/main.html
{%extends 'base.html'%}

{%block content%}


    <div class="main-btns">
        <div>
            <a href="{{ url_for('views.create_room')}}" class="create-btn btn btn-primary btn-lg">Create a room</a>
        </div>
        <div>
            <a href="{{ url_for('views.join_room')}}" class="join-btn btn btn-success ">Join a room</a>
        </div>
    </div>
    {{data.room}}

{%endblock%}

application/templates/room.html
{%extends 'base.html'%}


{%block content%}
<style>
    .room
    {
        margin-top: 5%;
    }
    .messages
    {   
        
        margin-top: 2%;
        margin-left: 5%;
        width: 50%;
        
        border-style: solid;
    }


    .message{
        width: 100%;
        display: table;
    }

    .message div {
        display: table-cell;
        width: 33%;
    }
.send-msg-form{
    width: 50%;
    margin-left: 5%;
    margin-right: 25%;
}

</style>
<div class="room">
    <div class="about-room" >
    <div class="room-title mt-2">
        <h3 style="margin-left: 5%;">Room:{{data.room.name}}</h3>
        <hr>
    </div>
    <div class="members" style="float: right; margin-right: 15%; width: 25%;">
        <h3>Members</h3>
        <hr>
        <table class="mems-table table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Member</th>
                <th scope="col">Active</th>
              </tr>
            </thead>
            <tbody>
                {%for user in data.room.users%}
                <tr id={{user.id}}>
                  <th scope="row">{{loop.index}}</th>
                  <td>@{{user.name}}</td>
                  <td>Yes</td>
                </tr>
                {%endfor%}

            </tbody>
          </table>
    </div>
    <div class="messages">
        {%for message in data.messages%}
        <div id={{message.id}} class="message">
        {%if g.user.id == message.owner_id %}
        

            <div class="message-date" style="width: 15%;">
                <p><small class="text-muted" style="margin-left: 15%;">{{message.date}}</small></p>
            </div>
            <div class="message-body" style="width: 70%;">
     
                <h6 class="message-text " style="float: right;" >{{message.content}}</h6> 
            </div>

            <div class="message-owner" >
                <h6 class="text-muted" style="float: right; margin-right: 15%; margin-top: 15%">{{message.owner.name}}</h6>
            </div>

        

        {%else%}

        <div class="message-owner" style="width: 15%;">
            <h6 class="text-muted" style="float: left; margin-left: 15%; margin-top: 15%">{{message.owner.name}}</h6>
        </div>

        <div class="message-body" style="width: 70%;">
 
            <h6 class="message-text " style="float: left;" >{{message.content}}</h6> 
        </div>

        <div class="message-date" style="width: 15%;">
            <p><small class="text-muted">{{message.date}}</small></p>
        </div>
        {%endif%}
    </div>
        {%if not loop.last%} <hr> {%endif%}
        {%endfor%}
       

    </div>
        <div class="send-msg-form form-inline mt-2">
            <div class="mb-3">
                <div class="message-div" style="width: 66%; float: left;">
                    <input type="text" class="form-control" id="new-message-body" placeholder="Enter Message">
                </div>
                <div class="send-btn-div">
                    <button id="send-btn"  style="float: right;" type="submit" class="btn btn-primary mb-2">Send</button>
                    <a onclick="leaveRoom(event, '{{g.user.id}}', '{{data.room.id}}')" href="{{ url_for('views.leave_room', user_id=g.user.id, room_id=data.room.id )}}" class="btn btn-danger me-2" style="float: right;">Leave the room</a>
                </div>
            </div>
            
        </div>
    
 
    </div>
    


    
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
function getCookie(name) {
  const value = `; ${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(';').shift();
}
    var socket = io.connect('http://127.0.0.1:5000');
    socket.on('connect', function() {

        fetch('/get_user')
            .then(response => response.json())
            .then(function(data){
                    socket.emit('new connection', {data: data});   
            
                //$('.mems-table').append(`<tr id=${data.user.id}> <th scope='row'> ${data.user.id} </th><td>${data.user.name}</td><td>Yes</td> </tr>`)
            }
            );

    });

        socket.on('new connection', function(user){
            console.log('new connection')
            if (!$(`#${user.id}`).length)
            $('.mems-table').append(`<tr id=${user.id}> <th scope='row'> ${user.id} </th><td>${user.name}</td><td>Yes</td> </tr>`)

        });
        socket.on('leave room', function(user){
            
            console.log(user.id, 'someone leaved the room')

            $(`#${user.id}`).remove()

        });

        socket.on('new message', function(data) {
            console.log('here')
            fetch('/get_user')
            .then(response => response.json())
            .then(function(user){
                
                if (user.user.id == data.msg.owner_id) { 
                    console.log('AYNI KISILER')
                    var message_div = `<div id=${data.msg.id} class="message"> <div class="message-date" style="width: 15%;"> <p><small class="text-muted">${data.msg.date}</small></p> </div> <div class="message-body" style="width: 70%;"> <h6 class="message-text " style="float: right;" >${data.msg.content}</h6> </div> <div class="message-owner" > <h6 class="text-muted" style="float: right; margin-right: 15%; margin-top: 15%">${data.creator_name}</h6> </div> </div>`
                    $('.messages').append(`${message_div}`)  
                    
                }
                else {
                    console.log('FARKLI KISILER')
                var message_div = `<div id=${data.msg.id} class="message"> <div class="message-owner" > <h6 class="text-muted" style="float: left; margin-left: 15%; margin-top: 15%">${data.creator_name}</h6> </div> <div class="message-body" style="width: 70%;"> <h6 class="message-text " style="float: left;" >${data.msg.content}</h6> </div> <div class="message-date" style="width: 15%;"> <p><small class="text-muted">${data.msg.date}</small></p> </div> </div> </div>`
                $('.messages').append(`${message_div}`) 
                }
            }
            );
        })

        $('#send-btn').on('click', function(){
            var newMsg = $('#new-message-body').val()
            data = {
                newMsg
            }
            socket.emit('new message', data)
            $('#new-message-body').val('')
        } )
</script>

{%endblock%}

application/templates/room2.html
{%extends 'base.html'%}


{%block content%}
<style>
    .room
    {
        margin-top: 5%;
    }
    .messages
    {   
        
        margin-top: 2%;
        margin-left: 5%;
        width: 50%;
        
        border-style: solid;

    }
    .message{
        width: 100%;
        display: table;
    }

    .message div {
        display: table-cell;
        width: 33%;
    }
.send-msg-form{
    width: 50%;
    margin-left: 5%;
    margin-right: 25%;
}

</style>
<div class="room">
    <div class="about-room" >
    <div class="room-title mt-2">
        <h3 style="margin-left: 5%;">Room:{{data.room.name}}</h3>
        <hr>
    </div>
    
    <div class="members" style="float: right; margin-right: 15%; width: 25%;">
        <h3>Members</h3>
        <hr>
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Member</th>
                <th scope="col">Active</th>
              </tr>
            </thead>
            <tbody>
                {%for user in data.room.users%}
              <tr>
                <th scope="row">{{loop.index }}</th>
                <td>@{{user.name}}</td>
                <td>Yes</td>
              </tr>
              {%endfor%}
            </tbody>
          </table>
    </div>
    </div>
    
    <div class="messages">
    <div class="message">
        <div class="message-owner" style=" width: 15%;">
            <h6 class="text-muted">Ali Ziya CEVIK</h6>
        </div>
        <div class="message-body" style="width: 70%;">
            <h3 id="message-text" style="margin-left:3%">a</h3>
        </div>
        <div class="message-date" style="width: 15%;">
            <p><small class="text-muted">14.04.2000</small></p>
        </div>
    </div>
    </div>
    <div class="send-msg-form form-inline mt-2">
    <div class="mb-3">
        <div class="message-div" style="width: 66%; float: left;">
            <input type="text" class="form-control" id="new-message-text" placeholder="Enter Message">
        </div>
        <div class="send-btn-div">
            <button id="send-btn"  style="float: right;" type="submit" class="btn btn-primary mb-2">Send</button>
            <a href="{{ url_for( 'views.leave_room' user_id= g.user.id, room_id= '{{room.id}}')}}" class="btn btn-danger me-2" style="float: right;">Leave the room</a>
        </div>
    </div>
    
    </div>
    
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js" integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA==" crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf-8">
var socket = io.connect('http://127.0.0.1:5000');
socket.on('connect', function() {
    socket.emit('my event', {data: 'I\'m connected!'});
    console.log('lala')
});

    $('#send-btn').on('click', function() {
    var new_msg = $('#new-message-text').val()
    console.log(new_msg)

    data = {
        new_msg,
    }

    socket.emit('new msg', data);
    $('#new-message-text').val('')

    })


</script>

{%endblock%}



    

    
 
    